pipeline {
    agent any

    environment {
        PROJECT_DIR = 'messaging_app'
        PYTHON_VERSION = 'python3'  // or 'python' depending on your system
    }

    stages {
        stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/alx-backend-python.git',
                    credentialsId: 'github-credentials',
                    branch: 'main',
                    changelog: true,
                    poll: false
                )
            }
        }

        stage('Install Dependencies') {
            steps {
                dir(PROJECT_DIR) {
                    sh '${PYTHON_VERSION} -m pip install --upgrade pip'
                    sh '${PYTHON_VERSION} -m pip install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir(PROJECT_DIR) {
                    sh '${PYTHON_VERSION} -m pytest tests/ --junitxml=test-results.xml'
                }
            }
            post {
                always {
                    junit "${PROJECT_DIR}/test-results.xml"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}